In [1]:
import tensorflow as tf
import numpy as np

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
vector = tf.constant([10, 7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [4]:
matrix = tf.constant(
    [
        [10, 7],
        [7, 10]
    ]
)
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [5]:
tensor = tf.constant([
    [
        [10, 10, 7],
        [5, 5, 6]
    ],
    [
        [2, 2, 1],
        [0, 0, 7]
    ]
])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[10, 10,  7],
        [ 5,  5,  6]],

       [[ 2,  2,  1],
        [ 0,  0,  7]]])>

In [6]:
print(scalar.shape)
print(scalar.ndim)

()
0


In [7]:
print(vector.shape)
print(vector.ndim)

(2,)
1


In [8]:
print(matrix.shape)
print(matrix.ndim)

(2, 2)
2


In [9]:
print(tensor.shape)
print(tensor.ndim)

(2, 2, 3)
3


In [10]:
constant_tensor = tf.constant([10, 7])
variable_tensor = tf.Variable([10, 7])
constant_tensor, variable_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>)

In [11]:
variable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [12]:
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [13]:
constant_tensor.assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [14]:
random1 = tf.random.Generator.from_seed(7)
random1 = random1.normal((2,3))
random1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1.3240396 ,  0.2878567 , -0.8757901 ],
       [-0.08857017,  0.69211644,  0.84215707]], dtype=float32)>

In [15]:
random2 = tf.random.Generator.from_seed(7)
random2 = random2.uniform((2,3))
random2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.39932835, 0.7840713 , 0.67880154],
       [0.73395896, 0.5520444 , 0.10948515]], dtype=float32)>

In [33]:
random2 == random1

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[False, False, False],
       [False, False, False]])>

## Shuffling the order of tensors

In [16]:
not_shuffled = tf.constant([
    [10, 7],
    [2, 4],
    [5, 9]
])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  4],
       [ 5,  9]])>

In [49]:
shuffled_tensor = tf.random.shuffle(not_shuffled)
shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  9],
       [10,  7],
       [ 2,  4]])>

In [52]:
tf.random.set_seed(42)
shuffled_tensor = tf.random.shuffle(not_shuffled, seed=40)
shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  9],
       [10,  7],
       [ 2,  4]])>

In [53]:
tf.ones(shape=(4,4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [54]:
tf.zeros(shape=(4,4))


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [59]:
import numpy as np
arr_a = np.arange(0, 50, dtype=np.int32).reshape(5,10)
arr_a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [62]:
tensor_x = tf.constant(arr_a, shape=(2, 5, 5))

In [63]:
print(tensor_x.shape)

(2, 5, 5)


In [64]:
tensor_x.ndim

3

In [68]:
tensor_x[:, 1]

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34]])>

In [69]:
tf.size(tensor_x)

<tf.Tensor: shape=(), dtype=int32, numpy=50>